app:
  name: 'tm-backend-trainee-impl-clean-template'
  version: '1.0.0'

http:
  port: '8081'

logger:
  log_level: 'debug'
  rollbar_env: 'tm-backend-trainee-impl-clean-template'

postgres:
  pool_max: 2

